apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: internetgateway
spec:
  forProvider:
    region: eu-central-1
    vpcIdRef:
      name: vpc
    tags:
      - key: Environment
        value: crossplane-example
      - key: Name
        value: internetgateway-crossplane
  providerConfigRef:
    name: awsconfig