apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: routetable
spec:
  forProvider:
    region: eu-central-1
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: internetgateway
    associations:
      - subnetIdRef:
          name: subnet
    vpcIdRef:
      name: vpc
    tags:
      - key: Environment
        value: crossplane-example
      - key: Name
        value: routetable-crossplane
  providerConfigRef:
    name: awsconfig